<?php include("top_bit.html"); ?>
    
    <div class="main box">
           
            <h1>Welcome to a guitar learning site</h1>
           
            
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent varius quam ut risus blandit, vitae condimentum odio pellentesque. Nunc a vulputate nulla. Phasellus vitae lectus et erat congue maximus quis quis ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ac sodales sem, in volutpat mauris. Duis neque velit, sodales porta pellentesque non, aliquet vitae dolor. Quisque finibus, velit nec laoreet viverra, turpis odio vulputate mauris, et commodo orci odio eget nisl. In sem lacus, mollis eu cursus eget, vulputate eu ipsum. Nunc sit amet arcu quis erat imperdiet fringilla. Phasellus nec consequat arcu.

Nullam condimentum tellus sit amet nulla laoreet, ut pellentesque dui consectetur. Sed eu malesuada nisl, vitae tincidunt mi. In hendrerit dui id risus ullamcorper, nec tristique risus scelerisque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras sit amet malesuada elit. Duis vestibulum, enim vitae fermentum tempor, tellus tellus hendrerit purus, quis hendrerit justo elit sit amet neque. Suspendisse potenti.

Nam venenatis lorem tortor, in lacinia est maximus ut. Curabitur pretium felis nec augue dapibus hendrerit. Fusce nec elit et massa dignissim dignissim. Donec malesuada vulputate nisl a mattis. Mauris accumsan sollicitudin nunc non porttitor. Duis lobortis elit a ex rutrum, ac ornare purus pellentesque. Curabitur vitae tellus sollicitudin odio accumsan malesuada id sit amet nunc. Nam volutpat ex eu nisl consequat, sit amet pretium elit varius. Integer vel ultrices eros.

Phasellus scelerisque sodales laoreet. In hac habitasse platea dictumst. Proin suscipit, ligula ac rutrum commodo, tortor metus varius diam, eget rhoncus ex eros at odio. Suspendisse finibus mollis diam sed dictum. Sed eget vehicula sapien. Aenean pharetra consequat malesuada. Aliquam erat volutpat. Ut ac arcu luctus, egestas nibh imperdiet, tincidunt urna. Phasellus dapibus tellus ut tortor lacinia, in dignissim elit porta. Nullam metus justo, gravida nec lorem in, imperdiet elementum metus. Suspendisse porttitor venenatis massa, malesuada blandit nisl rutrum sed.

Proin et est eu nulla fringilla sagittis a sed justo. Donec neque sem, venenatis a consectetur non, euismod in tortor. Aenean lacus est, posuere sed odio vitae, bibendum laoreet tellus. Curabitur eget est non odio ultricies rhoncus id sed mauris. Etiam faucibus lacus facilisis massa vulputate, nec cursus erat malesuada. Aenean gravida vehicula nibh at dignissim. Pellentesque maximus posuere turpis. Fusce quis mauris a arcu efficitur ultricies. Nullam sit amet felis bibendum, elementum velit a, dapibus nisi. Mauris ligula ipsum, porttitor vel bibendum nec, auctor vitae quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel mauris a diam feugiat blandit ut sed ex.

Phasellus a lacus vitae odio scelerisque auctor. Nullam semper lacus massa, tempor molestie augue sollicitudin quis. Suspendisse sodales finibus nisi sed varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean et metus hendrerit sem finibus scelerisque id tempus arcu. Nam nisi magna, convallis semper erat non, luctus imperdiet dui. Donec et justo a quam elementum tempus. Sed non mattis elit. Nunc accumsan, diam vitae commodo cursus, tellus nunc viverra eros, ut finibus dolor lorem eget purus. Donec accumsan consequat lectus, ac vehicula tortor aliquet id. Phasellus mollis elit vel gravida pretium. Phasellus tellus diam, cursus ac metus vitae, rutrum placerat eros. Nam vel maximus nibh, ac facilisis erat. Etiam sodales eros et nisl rhoncus, id placerat odio fringilla. In hac habitasse platea dictumst.

Cras luctus blandit lectus, vel tempor magna mattis eu. Sed eu ante a odio fermentum malesuada id non lacus. Sed scelerisque leo ac enim commodo porta a at dolor. Phasellus id ultricies erat. Donec sagittis aliquet ligula, quis mattis ante consectetur vel. Etiam sed orci ipsum. Aliquam maximus congue orci eget feugiat. Sed eget ultrices magna.

Morbi eget magna tellus. Donec elementum eu ligula non condimentum. Nam odio nisl, porta quis odio sit amet, venenatis finibus nisi. Pellentesque ultrices maximus lacus in iaculis. Donec metus turpis, lacinia eu euismod quis, facilisis id lectus. Pellentesque semper eros ac aliquet finibus. Suspendisse potenti. Nam odio felis, aliquet eget facilisis sed, molestie sit amet velit. Phasellus sagittis lorem risus, in sollicitudin lacus euismod et. Praesent eros ex, condimentum eu justo eget, posuere consequat quam. Nam purus eros, gravida id turpis id, scelerisque euismod sem.

Aenean eget rutrum sem. Pellentesque ac leo leo. Vivamus a odio gravida, facilisis libero eget, fermentum erat. Cras id accumsan urna. Sed tempor luctus rutrum. Aliquam finibus venenatis ex, et scelerisque eros venenatis sed. Aenean rutrum, magna eget tincidunt convallis, sem lacus sagittis libero, eget iaculis erat augue ut libero. Nulla felis ipsum, laoreet ac volutpat ac, congue lobortis enim. Phasellus quis nisl arcu. Fusce congue fringilla purus, sed facilisis neque pretium at. Donec leo sapien, dictum varius lacus vitae, convallis ultrices massa. Cras et nisl tempor, ullamcorper sem sagittis, bibendum est. Aliquam accumsan velit in arcu cursus, sit amet vehicula augue commodo. Aenean scelerisque ante tortor, et faucibus lacus rutrum id. Quisque sodales ornare dignissim.

Curabitur et lobortis nisi, et scelerisque neque. Praesent porttitor dolor in consequat auctor. Curabitur finibus semper fringilla. Nam lacinia facilisis dui, eu mattis arcu feugiat a. Sed in rhoncus purus. In malesuada at mauris ut pellentesque. Ut molestie diam ante, at interdum ex interdum nec. Nulla tincidunt feugiat velit, id iaculis magna finibus ut. Quisque porta dolor suscipit porta auctor. Donec auctor dictum nisl, in auctor tellus ornare eu. Ut malesuada elementum egestas. Duis aliquet aliquam pellentesque. Ut quis turpis vitae orci mattis tempus congue sit amet orci.
</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent varius quam ut risus blandit, vitae condimentum odio pellentesque. Nunc a vulputate nulla. Phasellus vitae lectus et erat congue maximus quis quis ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ac sodales sem, in volutpat mauris. Duis neque velit, sodales porta pellentesque non, aliquet vitae dolor. Quisque finibus, velit nec laoreet viverra, turpis odio vulputate mauris, et commodo orci odio eget nisl. In sem lacus, mollis eu cursus eget, vulputate eu ipsum. Nunc sit amet arcu quis erat imperdiet fringilla. Phasellus nec consequat arcu.</p>

</div>
          
        <div class="right-side box">
        <div class="center-content">
        <iframe width="575" height="315" src="https://www.youtube.com/embed/m80E1K75vDI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        
               </div>
               <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
       
                <p>
            </div>
<?php include("bottom_bit.html")?>       
 